### ISSUE TITLE
 "ppx_tools" is not available for your compiler or your OS.

### ISSUE THREAD

**Issue by ackoroa** [alainfrisch/ppx_tools#22]
When I tried installing ppx_tools using OPAM on UBUNTU 14.04 I get the above error message. Is ppx_tools not compatible with newer Ubuntu version or do I need to install something else beforehand?

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty

.# To complete the configuration of OPAM, you need to run:
eval `opam config env --root=/usr/.opam`
$ eval `opam config env --root=/usr/.opam`
$ sudo opam install --root=/usr/.opam ppx_tools
[ERROR] "ppx_tools" is not available for your compiler or your OS.
'opam install --root=/usr/.opam ppx_tools' failed.

**Comment by Drup** [comment]
What is your OCaml version ?

**Comment by ackoroa** [comment]
4.02.1

It's ok. We figured it's because we needed to upgrade opam first before installing ppx_tools. Sorry for the false alarm.
