### ISSUE TITLE
missing file metaquot_test.ml ?

### ISSUE THREAD

**Issue by zoggy** [alainfrisch/ppx_tools#25]
Hello,

https://github.com/alainfrisch/ppx_tools/blob/master/ppx_metaquot.ml refers to `metaquot_test.ml` which does not seem to be in the repository.

**Comment by TBads** [comment]
bump

**Comment by alainfrisch** [comment]
I don't find this file on any of my local working directories, so I guess it's lost for good.  I'll just remove the reference to it.
