### ISSUE TITLE
rewriter should exit non-0 at an error

### ISSUE THREAD

**Issue by camlspotter** [alainfrisch/ppx_tools#28]
It seems `rewriter` exits with status 0 and an empty output file even when the ppx command fails

```
$ ocamlfind ppx_tools/rewriter -ppx whatever -impl strange_input.ml -o strange_input.out.ml
File "", line 5, characters 15-17:
Error: Syntax error
```

Even it says `Error`, it exits with 0, which makes it hard to use in a build system...

**Comment by alainfrisch** [comment]
Thanks, this is now fixed!
