### ISSUE TITLE
The new versioning scheme is annoying

### ISSUE THREAD

**Issue by Drup** [alainfrisch/ppx_tools#35]
It means we can't put restriction over the ppx_tools versions. The versioning should use be something like `VERSION+COMPILER` instead.

**Comment by alainfrisch** [comment]
I expect there will be one major version of ppx_tools for each version of OCaml, so I'm only suggesting to use VERSION = the one from OCaml.  So if the version corresponding to 4.03.0 is "backported" to support 4.02.0 (by adding some abstraction layers, etc), it could be called 4.03.0+4.02.0.

**Comment by Drup** [comment]
And what does that gives us over "1.0+4.02" ? It seems really over complicated, and, as I said, it prevents proper version constraints.

**Comment by aantron** [comment]
I agree with @Drup. Currently porting Bisect_ppx to 4.03. The current version constraint looks worrisome for the backported 4.02 release, and it's not clear that this scheme can work if more than one backported release is made. The alternative 4.03.0+4.02.0 seems quite confusing – it is hard to immediately see which part of that means what. 1.0+4.02 has the advantages of being immediately readable, easy to order for constraints, and allowing major releases of ppx_tools without waiting for an OCaml version, should the need ever arise.

**Comment by alainfrisch** [comment]
Ok.  I guess that it would be a bad idea to have the next released version have a version number smaller than the current one, so let's start at 5.0 (I almost wanted to propose 4.03.0, but I thought this would be bad style) if everyone agrees.

**Comment by aantron** [comment]
Actually, I just did a quick grep for version constraints on ppx_tools dependencies, and I see that the only package using the new numbering scheme is the `bisect_ppx` version I just PR'd: https://github.com/ocaml/opam-repository/pull/6171

So, you might be able to sneak in a retroactive update... Are there other potential problems?

Otherwise, 5.0 seems fine :)

**Comment by aantron** [comment]
Well, I guess there are people's internal projects that aren't in OPAM.

**Comment by Drup** [comment]
@alainfrisch The starting number doesn't matter much, so whichever you prefer is fine. I would appreciate a release with @aantron's new interface soonish, though. :)

**Comment by alainfrisch** [comment]
I'd like to wait for #38 before creating a new release. @Drup Is it ok for you?

**Comment by aantron** [comment]
Any word on a release? At least Bisect_ppx and TyXML are blocked on it, AFAIK, and Markup.ml is also blocked transitively.

**Comment by alainfrisch** [comment]
A new release 5.0 is out, with a 5.0+4.02.0 variant.

**Comment by aantron** [comment]
Thanks!
