### ISSUE TITLE
Antiquotations for strings, ints, etc.

### ISSUE THREAD

**Issue by smolkaj** [alainfrisch/ppx_tools#52]
It would be useful to have antiquotations `[%int ...]`, `[%string ...]` and so on instead of just `[%e ...]`. This would simplify
```
let s' = Ast_convenience.str s in [%expr Foo [%e s']]
```
to just
```
[%expr Foo [%string s]]
```

**Comment by alainfrisch** [comment]
Assuming Ast_convenience is opened (likely if you use it), you can already write:

````ocaml
   [%expr Foo [%e str s]]
````

which is even shorter and does not require extra magic.

**Comment by smolkaj** [comment]
Ah, fantastic! I didn't understand the semantics of `[%e ...]` correctly.
